quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc.url: jdbc:postgresql://localhost:5432/quarkus_test
  hibernate-orm:
    database:
      generation: update
#quarkus.datasource.jdbc.max-size=16

